### ISSUE TITLE
PIL import issue

### ISSUE THREAD

**Issue by JamesOConnor** [developmentseed/fastai-serving#2]
Hi guys,

**Description:**

The torch version is pinned in the DockerFile, but pillow isn't. The latest version of pillow released a breaking change, as it removed the [PILLOW_VERSION param](https://pillow.readthedocs.io/en/stable/releasenotes/7.0.0.html#pillow-version-constant), which causes an import error.

**Solution:**

Pin pillow to 6.1 or upgrade the libs - I'll make a PR with the former and let you decide if you want to upgrade

**Comment by drewbo** [comment]
Thanks for flagging and fixing. Closed via #3
